<?php
/**
 * SET:IQ — Manage Playlists page (bulk delete / start over).
 *
 * SET:IQ ships a season's worth of playlists; this gives operators a
 * one-shot way to back them out instead of trashing two dozen
 * playlists by hand. Detection is local and offline-safe: every
 * generated playlist carries desc "Generated by SET:IQ", so nothing
 * here can touch a hand-made playlist. Deleting also removes the
 * schedule entries that reference the deleted playlists (and reloads
 * the scheduler), so no dangling rows are left behind.
 */

$FPP = 'http://127.0.0.1';

function setiq_mg_get($url) {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
        CURLOPT_HTTPHEADER     => ['Accept: application/json'],
    ]);
    $body = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return [$code, $body === false ? null : json_decode($body, true)];
}

function setiq_mg_delete_playlist($name) {
    $ch = curl_init('http://127.0.0.1/api/playlist/' . rawurlencode($name));
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST  => 'DELETE',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $code;
}

/** All SET:IQ-generated playlists on the box, with display metadata. */
function setiq_mg_scan($FPP) {
    list($code, $names) = setiq_mg_get("$FPP/api/playlists");
    if ($code !== 200 || !is_array($names)) return [null, "Couldn't list playlists (HTTP $code)"];

    // Scheduled-entry counts per playlist (one read for all rows).
    $schedCount = [];
    list($sc, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($sc === 200 && is_array($sched)) {
        foreach ($sched as $e) {
            $pl = is_array($e) ? ($e['playlist'] ?? '') : '';
            if ($pl !== '') $schedCount[$pl] = ($schedCount[$pl] ?? 0) + 1;
        }
    }

    $rows = [];
    foreach ($names as $name) {
        if (!is_string($name) || $name === '') continue;
        list($pc, $pl) = setiq_mg_get("$FPP/api/playlist/" . rawurlencode($name));
        if ($pc !== 200 || !is_array($pl)) continue;
        $desc = $pl['desc'] ?? '';
        if (strpos($desc, 'Generated by SET:IQ') !== 0) continue;
        $items = isset($pl['playlistInfo']['total_items'])
               ? (int) $pl['playlistInfo']['total_items']
               : count($pl['mainPlaylist'] ?? []);
        $dur = isset($pl['playlistInfo']['total_duration'])
             ? (int) round($pl['playlistInfo']['total_duration']) : 0;
        $rows[] = [
            'name'      => $name,
            'songs'     => $items,
            'duration'  => $dur,
            'scheduled' => $schedCount[$name] ?? 0,
        ];
    }
    usort($rows, function ($a, $b) { return strcasecmp($a['name'], $b['name']); });
    return [$rows, null];
}

function setiq_mg_fmt_dur($sec) {
    if ($sec <= 0) return '—';
    $m = intdiv($sec, 60);
    $s = $sec % 60;
    return $m >= 60
        ? sprintf('%d:%02d:%02d', intdiv($m, 60), $m % 60, $s)
        : sprintf('%d:%02d', $m, $s);
}

/** Drop schedule entries that reference the deleted playlists. */
function setiq_mg_clean_schedule($FPP, $deletedNames) {
    list($code, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($code !== 200 || !is_array($sched)) return 0;
    $gone = array_flip($deletedNames);
    $kept = [];
    $removed = 0;
    foreach ($sched as $e) {
        $pl = is_array($e) ? ($e['playlist'] ?? '') : '';
        if ($pl !== '' && isset($gone[$pl])) { $removed++; continue; }
        $kept[] = $e;
    }
    if ($removed === 0) return 0;

    $ch = curl_init("$FPP/api/schedule");
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => json_encode($kept),
        CURLOPT_HTTPHEADER     => ['Content-Type: application/json'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    curl_exec($ch);
    $rc = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($rc !== 200) return 0;

    // Non-fatal if fppd is stopped — the saved schedule loads next start.
    $ch = curl_init("$FPP/api/schedule/reload");
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => '',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 10,
    ]);
    curl_exec($ch);
    curl_close($ch);

    return $removed;
}

// ── Handle delete ─────────────────────────────────────────────────────

$results = [];
$notice = '';
$error = '';

if (($_POST['action'] ?? '') === 'delete') {
    $requested = isset($_POST['names']) && is_array($_POST['names'])
               ? array_filter($_POST['names'], 'is_string') : [];
    if (!$requested) {
        $error = 'Nothing selected.';
    } else {
        // Server-side re-verify against a fresh scan, so the form can
        // only ever delete playlists that are SET:IQ-generated right now.
        list($rows, $scanErr) = setiq_mg_scan($FPP);
        if ($rows === null) {
            $error = $scanErr;
        } else {
            $eligible = array_flip(array_column($rows, 'name'));
            $deleted = [];
            foreach ($requested as $name) {
                if (!isset($eligible[$name])) {
                    $results[] = [$name, 'skipped (not a SET:IQ playlist)'];
                    continue;
                }
                $rc = setiq_mg_delete_playlist($name);
                if ($rc === 200) {
                    $deleted[] = $name;
                    $results[] = [$name, 'deleted'];
                } else {
                    $results[] = [$name, "FAILED (HTTP $rc)"];
                }
            }
            $schedRemoved = $deleted ? setiq_mg_clean_schedule($FPP, $deleted) : 0;
            $notice = count($deleted) . ' playlist(s) deleted'
                    . ($schedRemoved ? ", $schedRemoved schedule entr" . ($schedRemoved === 1 ? 'y' : 'ies') . ' removed' : '')
                    . '.';
        }
    }
}

// Fresh list for the table (post-delete it reflects what's left).
list($rows, $scanErr) = setiq_mg_scan($FPP);
if ($rows === null && $error === '') $error = $scanErr;
?>
<div class="container-fluid">
  <h2>SET:IQ — Manage Playlists</h2>
  <p>Every playlist SET:IQ has created on this box (detected by its
     &ldquo;Generated by SET:IQ&rdquo; description — hand-made playlists never
     appear here). Select what to remove and delete in one shot; matching
     schedule entries are cleaned up too. Re-pulling recreates everything.</p>

  <?php if ($error): ?>
    <div class="alert alert-danger" style="border:1px solid rgba(127,127,127,.4);background:rgba(127,127,127,.12);padding:10px 14px;border-radius:6px;max-width:720px"><?= htmlspecialchars($error) ?></div>
  <?php endif; ?>

  <?php if ($notice): ?>
    <div class="alert alert-success" style="border:1px solid rgba(127,127,127,.4);background:rgba(127,127,127,.12);padding:10px 14px;border-radius:6px;max-width:720px"><?= htmlspecialchars($notice) ?></div>
  <?php endif; ?>

  <?php if ($results): ?>
    <table class="table table-striped" style="max-width:720px">
      <thead><tr><th>Playlist</th><th>Result</th></tr></thead>
      <tbody>
      <?php foreach ($results as $r): ?>
        <tr><td><?= htmlspecialchars($r[0]) ?></td><td><?= htmlspecialchars($r[1]) ?></td></tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>

  <?php if ($rows !== null && !$rows): ?>
    <p><i>No SET:IQ-generated playlists on this box.</i></p>
  <?php elseif ($rows): ?>
    <form method="post" id="setiq-manage-form"
          onsubmit="return confirm('Delete ' + document.querySelectorAll('#setiq-manage-form input[name=\'names[]\']:checked').length + ' playlist(s)? Matching schedule entries are removed too. Re-pulling from SET:IQ recreates them.');">
      <input type="hidden" name="action" value="delete">
      <table class="table table-striped" style="max-width:880px">
        <thead>
          <tr>
            <th style="width:36px">
              <input type="checkbox" id="setiq-check-all" checked
                     title="Select all / none"
                     onclick="document.querySelectorAll('#setiq-manage-form input[name=\'names[]\']').forEach(c => c.checked = this.checked)">
            </th>
            <th>Playlist</th>
            <th>Songs</th>
            <th>Duration</th>
            <th>Schedule entries</th>
          </tr>
        </thead>
        <tbody>
        <?php foreach ($rows as $r): ?>
          <tr>
            <td><input type="checkbox" name="names[]" value="<?= htmlspecialchars($r['name']) ?>" checked></td>
            <td><?= htmlspecialchars($r['name']) ?></td>
            <td><?= (int) $r['songs'] ?></td>
            <td><?= htmlspecialchars(setiq_mg_fmt_dur($r['duration'])) ?></td>
            <td><?= $r['scheduled'] ? (int) $r['scheduled'] : '—' ?></td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
      <button type="submit" class="buttons btn btn-danger">Delete selected playlists</button>
    </form>
    <p style="margin-top:1em"><small>All rows are selected by default — uncheck
       anything you want to keep. Deleting the <code>REQIQ Requests</code>
       playlist is safe; the REQ:IQ listener rebuilds it automatically while
       enabled.</small></p>
  <?php endif; ?>
</div>
