<?php
/**
 * SET:IQ — Manage Playlists page (bulk delete / start over).
 *
 * SET:IQ ships a season's worth of playlists; this gives operators a
 * one-shot way to back them out instead of trashing two dozen
 * playlists by hand. Detection is local and offline-safe: every
 * generated playlist carries desc "Generated by SET:IQ", so nothing
 * here can touch a hand-made playlist. Deleting also removes the
 * schedule entries that reference the deleted playlists (and reloads
 * the scheduler), so no dangling rows are left behind.
 *
 * It ALSO clears SET:IQ's triggers — the scheduled "Command" rows that
 * adjust volume, fire presets, etc. Those carry an empty playlist, so the
 * prefix rule above can't see them; left alone they pile up on every pull
 * and can't be deleted from the box ("they keep coming back"). SET:IQ now
 * schedules each trigger through a named "<Show> - …" Command Preset (via
 * "Run Command Preset"), so we can recognize, list and delete them here —
 * the preset and every scheduler row that fires it — plus surface any
 * legacy/raw command rows so the operator can clear those too.
 */

$FPP = 'http://127.0.0.1';

if (!defined('SETIQ_RUN_PRESET_CMD')) define('SETIQ_RUN_PRESET_CMD', 'Run Command Preset');
// Marker SET:IQ stamps on the presets it creates (pull.php), so we can tell
// our trigger presets from the operator's own hand-built ones.
if (!defined('SETIQ_PRESET_DESC')) define('SETIQ_PRESET_DESC', 'SET:IQ trigger');

function setiq_mg_get($url) {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
        CURLOPT_HTTPHEADER     => ['Accept: application/json'],
    ]);
    $body = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return [$code, $body === false ? null : json_decode($body, true)];
}

/** POST a JSON body to an FPP endpoint; returns the HTTP code. */
function setiq_mg_post_json($url, $payload) {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => json_encode($payload),
        CURLOPT_HTTPHEADER     => ['Content-Type: application/json'],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $code;
}

function setiq_mg_delete_playlist($name) {
    $ch = curl_init('http://127.0.0.1/api/playlist/' . rawurlencode($name));
    curl_setopt_array($ch, [
        CURLOPT_CUSTOMREQUEST  => 'DELETE',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,
    ]);
    curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $code;
}

/** All SET:IQ-generated playlists on the box, with display metadata. */
function setiq_mg_scan($FPP) {
    list($code, $names) = setiq_mg_get("$FPP/api/playlists");
    if ($code !== 200 || !is_array($names)) return [null, "Couldn't list playlists (HTTP $code)"];

    // Scheduled-entry counts per playlist (one read for all rows).
    $schedCount = [];
    list($sc, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($sc === 200 && is_array($sched)) {
        foreach ($sched as $e) {
            $pl = is_array($e) ? ($e['playlist'] ?? '') : '';
            if ($pl !== '') $schedCount[$pl] = ($schedCount[$pl] ?? 0) + 1;
        }
    }

    $rows = [];
    foreach ($names as $name) {
        if (!is_string($name) || $name === '') continue;
        list($pc, $pl) = setiq_mg_get("$FPP/api/playlist/" . rawurlencode($name));
        if ($pc !== 200 || !is_array($pl)) continue;
        $desc = $pl['desc'] ?? '';
        if (strpos($desc, 'Generated by SET:IQ') !== 0) continue;
        $items = isset($pl['playlistInfo']['total_items'])
               ? (int) $pl['playlistInfo']['total_items']
               : count($pl['mainPlaylist'] ?? []);
        $dur = isset($pl['playlistInfo']['total_duration'])
             ? (int) round($pl['playlistInfo']['total_duration']) : 0;
        $rows[] = [
            'name'      => $name,
            'songs'     => $items,
            'duration'  => $dur,
            'scheduled' => $schedCount[$name] ?? 0,
        ];
    }
    usort($rows, function ($a, $b) { return strcasecmp($a['name'], $b['name']); });
    return [$rows, null];
}

/** Read the box's Command Presets as a flat array (tolerant of either the
 *  { commandPresets: [...] } wrapper or a bare array). */
function setiq_mg_read_presets($FPP) {
    list($code, $cfg) = setiq_mg_get("$FPP/api/configfile/commandPresets.json");
    if ($code !== 200 || !is_array($cfg)) return [];
    if (isset($cfg['commandPresets']) && is_array($cfg['commandPresets'])) return $cfg['commandPresets'];
    return $cfg;
}

/** The names of the presets SET:IQ created (by our description marker). */
function setiq_mg_setiq_preset_names($presets) {
    $names = [];
    foreach ($presets as $p) {
        if (!is_array($p)) continue;
        $name = (string) ($p['name'] ?? '');
        $desc = (string) ($p['description'] ?? '');
        if ($name !== '' && $desc === SETIQ_PRESET_DESC) $names[$name] = true;
    }
    return $names;
}

/** Is a schedule row a "Command" row (empty playlist + a command)? */
function setiq_mg_is_command_row($e) {
    if (!is_array($e)) return false;
    $pl = (string) ($e['playlist'] ?? '');
    $cmd = (string) ($e['command'] ?? '');
    return $pl === '' && $cmd !== '';
}

/** Stable signature for a command row, so we can match (and delete every
 *  duplicate of) the exact trigger the operator picked. */
function setiq_mg_cmd_sig($e) {
    $cmd  = (string) ($e['command'] ?? '');
    $args = (isset($e['args']) && is_array($e['args'])) ? array_map('strval', $e['args']) : [];
    return implode('|', [
        $cmd, implode(',', $args),
        (string) ($e['day'] ?? ''), (string) ($e['startTime'] ?? ''),
        (string) ($e['startDate'] ?? ''), (string) ($e['endDate'] ?? ''),
    ]);
}

/**
 * Every "Command" row in the schedule, with a SET:IQ flag. A row is SET:IQ's
 * when it fires one of our presets ("Run Command Preset" → a SET:IQ preset
 * name). Legacy/raw rows (older pulls wrote the command inline) are still
 * listed so the operator can clear the leftovers — just not pre-checked.
 */
function setiq_mg_scan_commands($FPP, $setiqPresetNames) {
    list($sc, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($sc !== 200 || !is_array($sched)) return [];
    $rows = [];
    $seen = [];
    foreach ($sched as $e) {
        if (!setiq_mg_is_command_row($e)) continue;
        $sig = setiq_mg_cmd_sig($e);
        $cmd  = (string) ($e['command'] ?? '');
        $args = (isset($e['args']) && is_array($e['args'])) ? array_map('strval', $e['args']) : [];
        $isSetiq = ($cmd === SETIQ_RUN_PRESET_CMD)
                && isset($args[0]) && isset($setiqPresetNames[$args[0]]);
        // The display label: the fired preset for our rows, else the raw command.
        $label = $isSetiq ? $args[0] : trim($cmd . ' ' . implode(' ', $args));
        if (isset($seen[$sig])) { $rows[$seen[$sig]]['count']++; continue; }
        $seen[$sig] = count($rows);
        $rows[] = [
            'sig'     => $sig,
            'label'   => $label,
            'when'    => (string) ($e['startTime'] ?? ''),
            'dates'   => trim((string) ($e['startDate'] ?? '') . ' → ' . (string) ($e['endDate'] ?? ''), ' →'),
            'setiq'   => $isSetiq,
            'count'   => 1,
        ];
    }
    usort($rows, function ($a, $b) {
        if ($a['setiq'] !== $b['setiq']) return $a['setiq'] ? -1 : 1;
        return strcasecmp($a['label'], $b['label']);
    });
    return $rows;
}

function setiq_mg_fmt_dur($sec) {
    if ($sec <= 0) return '—';
    $m = intdiv($sec, 60);
    $s = $sec % 60;
    return $m >= 60
        ? sprintf('%d:%02d:%02d', intdiv($m, 60), $m % 60, $s)
        : sprintf('%d:%02d', $m, $s);
}

/**
 * Rewrite the schedule, dropping (a) rows that reference a deleted playlist
 * and (b) command rows whose signature the operator selected. One read +
 * one write + one reload. Returns how many rows were removed.
 */
function setiq_mg_clean_schedule($FPP, $deletedNames, $cmdSigs = []) {
    list($code, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($code !== 200 || !is_array($sched)) return 0;
    $gone = array_flip($deletedNames);
    $sigs = array_flip($cmdSigs);
    $kept = [];
    $removed = 0;
    foreach ($sched as $e) {
        $pl = is_array($e) ? ($e['playlist'] ?? '') : '';
        if ($pl !== '' && isset($gone[$pl])) { $removed++; continue; }
        if (setiq_mg_is_command_row($e) && isset($sigs[setiq_mg_cmd_sig($e)])) { $removed++; continue; }
        $kept[] = $e;
    }
    if ($removed === 0) return 0;

    if (setiq_mg_post_json("$FPP/api/schedule", $kept) !== 200) return 0;

    // Non-fatal if fppd is stopped — the saved schedule loads next start.
    $ch = curl_init("$FPP/api/schedule/reload");
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => '',
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 10,
    ]);
    curl_exec($ch);
    curl_close($ch);

    return $removed;
}

/**
 * Prune SET:IQ presets that no surviving schedule row still fires. Run AFTER
 * the schedule rewrite, so clearing a trigger's rows also removes its preset —
 * "kill it permanently". Operator presets are never touched. Returns the count
 * removed.
 */
function setiq_mg_prune_presets($FPP) {
    $presets = setiq_mg_read_presets($FPP);
    if (!$presets) return 0;
    $setiqNames = setiq_mg_setiq_preset_names($presets);
    if (!$setiqNames) return 0;

    // Which SET:IQ presets are still referenced by a Run Command Preset row.
    $referenced = [];
    list($sc, $sched) = setiq_mg_get("$FPP/api/schedule");
    if ($sc === 200 && is_array($sched)) {
        foreach ($sched as $e) {
            if (!is_array($e) || ($e['command'] ?? '') !== SETIQ_RUN_PRESET_CMD) continue;
            $args = (isset($e['args']) && is_array($e['args'])) ? $e['args'] : [];
            if (isset($args[0])) $referenced[(string) $args[0]] = true;
        }
    }

    $kept = [];
    $removed = 0;
    foreach ($presets as $p) {
        $name = is_array($p) ? (string) ($p['name'] ?? '') : '';
        if ($name !== '' && isset($setiqNames[$name]) && !isset($referenced[$name])) {
            $removed++;
            continue;
        }
        $kept[] = $p;
    }
    if ($removed === 0) return 0;

    setiq_mg_post_json("$FPP/api/configfile/commandPresets.json", ['commandPresets' => array_values($kept)]);
    return $removed;
}

// ── Handle delete ─────────────────────────────────────────────────────

$results = [];
$notice = '';
$error = '';

if (($_POST['action'] ?? '') === 'delete') {
    $requested = isset($_POST['names']) && is_array($_POST['names'])
               ? array_filter($_POST['names'], 'is_string') : [];
    $reqSigs   = isset($_POST['cmdsigs']) && is_array($_POST['cmdsigs'])
               ? array_values(array_filter($_POST['cmdsigs'], 'is_string')) : [];
    if (!$requested && !$reqSigs) {
        $error = 'Nothing selected.';
    } else {
        // Server-side re-verify against a fresh scan, so the form can
        // only ever delete playlists that are SET:IQ-generated right now.
        list($rows, $scanErr) = setiq_mg_scan($FPP);
        if ($rows === null) {
            $error = $scanErr;
        } else {
            $eligible = array_flip(array_column($rows, 'name'));
            $deleted = [];
            foreach ($requested as $name) {
                if (!isset($eligible[$name])) {
                    $results[] = [$name, 'skipped (not a SET:IQ playlist)'];
                    continue;
                }
                $rc = setiq_mg_delete_playlist($name);
                if ($rc === 200) {
                    $deleted[] = $name;
                    $results[] = [$name, 'deleted'];
                } else {
                    $results[] = [$name, "FAILED (HTTP $rc)"];
                }
            }
            // One schedule rewrite handles both the deleted playlists' rows
            // and the selected command/trigger rows (every duplicate of each).
            $schedRemoved = ($deleted || $reqSigs)
                          ? setiq_mg_clean_schedule($FPP, $deleted, $reqSigs) : 0;
            // Drop any SET:IQ preset left with no row firing it.
            $presetsRemoved = setiq_mg_prune_presets($FPP);

            $parts = [];
            if ($deleted)         $parts[] = count($deleted) . ' playlist(s) deleted';
            if ($schedRemoved)    $parts[] = "$schedRemoved schedule entr" . ($schedRemoved === 1 ? 'y' : 'ies') . ' removed';
            if ($presetsRemoved)  $parts[] = "$presetsRemoved trigger preset" . ($presetsRemoved === 1 ? '' : 's') . ' cleared';
            $notice = ($parts ? implode(', ', $parts) : 'Nothing to remove') . '.';
        }
    }
}

// Fresh lists for the tables (post-delete they reflect what's left).
list($rows, $scanErr) = setiq_mg_scan($FPP);
if ($rows === null && $error === '') $error = $scanErr;
$presets   = setiq_mg_read_presets($FPP);
$cmdRows   = setiq_mg_scan_commands($FPP, setiq_mg_setiq_preset_names($presets));
$setiqCmds = array_values(array_filter($cmdRows, function ($r) { return $r['setiq']; }));
$otherCmds = array_values(array_filter($cmdRows, function ($r) { return !$r['setiq']; }));
?>
<div class="container-fluid">
 <div class="iq-pane">
  <h2 class="iq-h2">SET<span class="iq-c-set">:</span>IQ — Manage Playlists</h2>
  <p class="iq-lede">Every playlist SET:IQ created on this box (detected by its
     &ldquo;Generated by SET:IQ&rdquo; description — hand-made playlists never
     appear here), plus the <b>triggers</b> it scheduled (volume, presets, etc.).
     All SET:IQ rows are pre-selected; uncheck keepers and delete the rest.
     Matching schedule entries and trigger presets are cleaned up too, and
     re-pulling recreates everything.</p>

  <?php if ($error): ?>
    <div class="setiq-alert setiq-alert-err" style="margin-top:14px"><?= htmlspecialchars($error) ?></div>
  <?php endif; ?>

  <?php if ($notice): ?>
    <div class="setiq-alert setiq-alert-ok" style="margin-top:14px"><?= htmlspecialchars($notice) ?></div>
  <?php endif; ?>

  <?php if ($results): ?>
    <div class="iq-tablewrap" style="margin-top:14px;max-width:720px">
      <table class="table table-striped">
        <thead><tr><th>Playlist</th><th>Result</th></tr></thead>
        <tbody>
        <?php foreach ($results as $r): ?>
          <tr><td class="iq-name"><?= htmlspecialchars($r[0]) ?></td><td><?= htmlspecialchars($r[1]) ?></td></tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  <?php endif; ?>

  <?php
    $hasPlaylists = $rows !== null && $rows;
    $hasTriggers  = $setiqCmds || $otherCmds;
  ?>

  <?php if (!$hasPlaylists && !$hasTriggers): ?>
    <p class="iq-fine" style="margin-top:18px"><i>No SET:IQ-generated playlists or triggers on this box.</i></p>
  <?php else: ?>

    <?php
      $totalDur   = $hasPlaylists ? array_sum(array_column($rows, 'duration')) : 0;
      $totalSched = $hasPlaylists ? array_sum(array_column($rows, 'scheduled')) : 0;
    ?>
    <div class="iq-chips">
      <div class="iq-chip"><span class="iq-chip-num"><?= $hasPlaylists ? count($rows) : 0 ?></span><span class="iq-chip-lbl">generated playlists</span></div>
      <div class="iq-chip"><span class="iq-chip-num"><?= htmlspecialchars(setiq_mg_fmt_dur($totalDur)) ?></span><span class="iq-chip-lbl">total runtime</span></div>
      <div class="iq-chip"><span class="iq-chip-num"><?= count($setiqCmds) ?></span><span class="iq-chip-lbl">SET:IQ triggers</span></div>
    </div>

    <form method="post" id="setiq-manage-form"
          onsubmit="return confirm('Delete the selected playlists and triggers? Matching schedule entries and trigger presets are removed too. Re-pulling from SET:IQ recreates them.');">
      <input type="hidden" name="action" value="delete">

      <?php if ($hasPlaylists): ?>
      <h3 class="iq-h3" style="margin-top:18px">Playlists</h3>
      <div class="iq-tablewrap">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width:40px" class="iq-num">
                <input type="checkbox" class="setiq-check-all" data-group="names" checked
                       title="Select all / none"
                       onclick="document.querySelectorAll('#setiq-manage-form input[name=\'names[]\']').forEach(c => c.checked = this.checked)">
              </th>
              <th>Playlist</th>
              <th class="iq-num">Songs</th>
              <th class="iq-num">Duration</th>
              <th class="iq-num">Schedule</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td class="iq-num"><input type="checkbox" name="names[]" value="<?= htmlspecialchars($r['name']) ?>" checked></td>
              <td class="iq-name"><?= htmlspecialchars($r['name']) ?></td>
              <td class="iq-num"><?= (int) $r['songs'] ?></td>
              <td class="iq-num"><?= htmlspecialchars(setiq_mg_fmt_dur($r['duration'])) ?></td>
              <td class="iq-num"><?= $r['scheduled'] ? (int) $r['scheduled'] : '—' ?></td>
            </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
      </div>
      <?php endif; ?>

      <?php if ($hasTriggers): ?>
      <h3 class="iq-h3" style="margin-top:22px">Triggers &amp; scheduled commands</h3>
      <p class="iq-fine" style="margin-bottom:8px">Scheduled <b>Command</b> rows. SET:IQ's
         own triggers fire a <code>SET:IQ</code> preset and are pre-selected;
         any other command rows below are shown so you can clear leftovers from
         older pulls, but are left unchecked — only check what you recognize as
         SET:IQ's. Deleting a trigger removes every duplicate of it.</p>
      <div class="iq-tablewrap">
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="width:40px" class="iq-num">
                <input type="checkbox" class="setiq-check-all" data-group="cmdsigs"
                       title="Select all / none of the trigger rows"
                       onclick="document.querySelectorAll('#setiq-manage-form input[name=\'cmdsigs[]\']').forEach(c => c.checked = this.checked)">
              </th>
              <th>Command / preset</th>
              <th>Time</th>
              <th>Dates</th>
              <th class="iq-num">Rows</th>
              <th>Origin</th>
            </tr>
          </thead>
          <tbody>
          <?php foreach (array_merge($setiqCmds, $otherCmds) as $c): ?>
            <tr>
              <td class="iq-num"><input type="checkbox" name="cmdsigs[]" value="<?= htmlspecialchars($c['sig']) ?>" <?= $c['setiq'] ? 'checked' : '' ?>></td>
              <td class="iq-name"><?= htmlspecialchars($c['label'] !== '' ? $c['label'] : '(command)') ?></td>
              <td><?= htmlspecialchars($c['when'] !== '' ? $c['when'] : '—') ?></td>
              <td><?= htmlspecialchars($c['dates'] !== '' ? $c['dates'] : '—') ?></td>
              <td class="iq-num"><?= (int) $c['count'] ?></td>
              <td><?= $c['setiq']
                    ? '<span class="iq-badge iq-badge-ok">SET:IQ</span>'
                    : '<span class="iq-badge iq-badge-upd">other</span>' ?></td>
            </tr>
          <?php endforeach; ?>
          </tbody>
        </table>
      </div>
      <?php endif; ?>

      <div class="iq-actionrow" style="margin-top:14px">
        <button type="submit" class="buttons btn btn-danger">Delete selected</button>
        <span class="iq-fine">Deleting the <code>REQIQ Requests</code> playlist is
          safe — the listener rebuilds it.</span>
      </div>
    </form>
    <p class="iq-fine" style="margin-top:14px">SET:IQ rows are selected by default —
       uncheck anything you want to keep. The REQ:IQ listener rebuilds its
       <code>REQIQ Requests</code> playlist automatically while enabled.</p>
  <?php endif; ?>
 </div>
</div>
